### PR TITLE
Release 4.0.0

### PR DESCRIPTION
**Pull request by baurmatt**
Major version because we drop support for 14.04

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @baurmatt. It would be nice if we could include the latest modulesync https://github.com/voxpupuli/puppet-python/pull/525 in this release. Do you have some time to look into it? Otherwise I might be able to do it in the next days.

**Comment by baurmatt** [comment]
Hey @bastelfreak, sure! :) I've just added an additional commit which fixed the tests.

**Comment by bastelfreak** [comment]
thanks, can you please rebase this PR and regenerate the changelog? Afterwards we can merge and release.

**Comment by baurmatt** [comment]
@bastelfreak Done! :) Could you please restart the failing Travis tests? Doesn't look like a really error, just a Forge Timeout.

**Comment by bastelfreak** [comment]
I executed the travis_release task

**Pull request merged**
