### PR TITLE
Add single quotation for pip url

### PR DESCRIPTION
**Pull request by onstring**
Will fix the pip installation issue when url is `git+https://github.com/xxxxxxxx#egg=yyyy`

### CODE REVIEW

**Comment by alexjfisher** [comment]
Does the regex 
https://github.com/voxpupuli/puppet-python/pull/429/files#diff-8a5246728de7306981fd3fa2191bd8eaR214 need adjusting?

**Comment by danquack** [comment]
@onstring you can proabably fix the robocop errors with ``` bundle exec rake rubocop:auto_correct```

**Comment by bastelfreak** [comment]
mhm, would an acceptance test be helpful here?

**Comment by onstring** [comment]
The patch is fixing the breakage when url is like `git+https://github.com/xxxxxxxx#egg=yyyy`

**Comment by alexjfisher** [comment]
and https://github.com/voxpupuli/puppet-python/pull/429/files#diff-8a5246728de7306981fd3fa2191bd8eaR214 ? This would have matched previously (when $source == $url), but won't anymore.

**Pull request closed without merging**
