### PR TITLE
Remove resource collector overriding pip_provider

### LINKED ISSUE #505: Wrong pip referenced inside virtualenv
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.16
- Distribution: CentOS
- Module version: 3.0.1

## How to reproduce (e.g Puppet code you use)
```
python::virtualenv {'es_stats_venv':
	version => '3.4',
	virtualenv => 'virtualenv-3.4',
	venv_dir => '/etc/zabbix/es_stats_venv',
	owner => 'zabbix',
}

python::pip { 'es_stats_zabbix' :
	ensure => 'present',
	pkgname  => 'es_stats_zabbix',
	owner => 'root',
	pip_provider  => 'pip3',
	virtualenv => '/etc/zabbix/es_stats_venv',
}

python::pip { 'es_stats' :
	ensure => 'present',
	pkgname  => 'es_stats',
	owner => 'root',
	pip_provider  => 'pip3',
	virtualenv => '/etc/zabbix/es_stats_venv',
}
```

## What are you seeing
```
Error: /Stage[main]/Graylog_els_cluster_node/Python::Pip[es_stats_zabbix]/Exec[pip_install_es_stats_zabbix]: Could not evaluate: Could not find command '/etc/zabbix/es_stats_venv/bin/pip3.6'
Error: /Stage[main]/Graylog_els_cluster_node/Python::Pip[es_stats]/Exec[pip_install_es_stats]: Could not evaluate: Could not find command '/etc/zabbix/es_stats_venv/bin/pip3.6'
```

## What behaviour did you expect instead
No errors, execution of pip at the valid path of `/etc/zabbix/es_stats_venv/bin/pip3` which exists inside the venv.

I've also tried to specify `pip3.4` as the `pip_provider`, which is valid inside the venv. Specifying this has no affect on the outcome.

Other virtualenvs are affected also, this is just an example showing similar symptoms.

### PR DESCRIPTION
**Pull request by jplindquist**
#### Pull Request (PR) description
Remove resource collector overriding `pip_provider` parameter in `Python::Pip`

#### This Pull Request (PR) fixes the following issues
Fixes #505 

There seems to be an unrelated acceptance test failing locally for me (it's failing on master as well):
```
Failures:

  1) python class default parameters works with ensure=>latest for package with underscore in its name
     Failure/Error: apply_manifest(pp, catch_failures: true)
     Beaker::Host::CommandFailure:
       Host 'debian9-64-1' exited with 6 running:
        puppet apply --verbose --detailed-exitcodes /tmp/apply_manifest.pp.si5Ebi
       Last 10 lines of output were:
       	Info: Applying configuration version '1571415656'
       	Notice: /Stage[main]/Main/Python::Virtualenv[venv]/File[/opt/venv4]/ensure: created
       	Notice: /Stage[main]/Main/Python::Virtualenv[venv]/Exec[python_virtualenv_/opt/venv4]/returns: executed successfully
       	Notice: /Stage[main]/Main/Python::Pip[Randomized_Requests]/Exec[pip_install_Randomized_Requests]/returns: DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
       	Notice: /Stage[main]/Main/Python::Pip[Randomized_Requests]/Exec[pip_install_Randomized_Requests]/returns: ERROR: Could not find a version that satisfies the requirement Randomized_Requests (from versions: none)
       	Notice: /Stage[main]/Main/Python::Pip[Randomized_Requests]/Exec[pip_install_Randomized_Requests]/returns: ERROR: No matching distribution found for Randomized_Requests
       	Error: '/opt/venv4/bin/pip --log /opt/venv4/pip.log install --upgrade     Randomized_Requests' returned 1 instead of one of [0]
       	Error: /Stage[main]/Main/Python::Pip[Randomized_Requests]/Exec[pip_install_Randomized_Requests]/returns: change from 'notrun' to ['0'] failed: '/opt/venv4/bin/pip --log /opt/venv4/pip.log install --upgrade     Randomized_Requests' returned 1 instead of one of [0]
       	Info: Class[Main]: Unscheduling all events on Class[Main]
       	Notice: Applied catalog in 4.40 seconds
```

### CODE REVIEW

**Comment by saz** [comment]
What's required to get this merged?

**Comment by igalic** [comment]
@saz somebody to review this code and approve of it.
Somebody (else) to figure out why acceptance tests are failing on 'debian9-64-1'… though this is lower priority, and not a blocker.
Does it maybe not have python2.7?

**Comment by saz** [comment]
The suggested change is working for me with pip 18.1 and 20.0.2.
Before this change, package installations where broken on pip 18.1

Tests are failing due to the deprecation of Python 2

**Comment by jplindquist** [comment]
Is there anything I need to do as well to help move this along?

**Comment by bastelfreak** [comment]
@jplindquist I fixed the test on master and rebased your branch.

**Pull request merged**
