### PR TITLE
Add python-venv installation

### PR DESCRIPTION
**Pull request by crazymind1337**
#### Pull Request (PR) description
If you use `python::pyvenv` you require the package `python-venv` (name differs on OSes). This has been missing.

### CODE REVIEW

**Comment by bastelfreak** [comment]
@crazymind1337 can you please rebase against our latest master branch?

**Comment by crazymind1337** [comment]
> @crazymind1337 can you please rebase against our latest master branch?

Done.

**Comment by bastelfreak** [comment]
can you take a look at the failing tests? They are passing on master

**Comment by crazymind1337** [comment]
Oh yes. Will be done next week.

**Comment by crazymind1337** [comment]
Looks like I forgot something :D

**Review by bastelfreak — APPROVED** [review]
looks good to me. I don't see any backwards-incompatible changes, but I'm also not a python expert. Can you verify that this won't break existing installations?

**Comment by crazymind1337** [comment]
It would break it so far, if you already have defined a `Package[python3-venv]` resource, you would run into a duplicate resource. But this is what the fix is for.

**Pull request merged**
