### PR TITLE
Implement Ubuntu 20.04 support

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by bastelfreak** [comment]
I think before we implement this properly we should drop the python::virtualenv resource as it's really really end of life. otherwise we need to add a huge amount of workarounds.

**Comment by DnZmfr** [comment]
Hi,
Do you have any idea when this fix for ubuntu 20.04 will be released?

Thanks.
Dan

**Comment by kenyon** [comment]
> Do you have any idea when this fix for ubuntu 20.04 will be released?

Not before the tests pass, at least.

**Comment by bastelfreak** [comment]
@DnZmfr I'm a bit low on available time since I also maintain other modules. If you're interested in picking this up or dropping python::virtualenv in another PR, that would be highly appreciated :)

**Comment by treydock** [comment]
@bastelfreak I would think it's not possible to get rid of `python::virtualenv` unless it's okay to force RHEL 7 sites to use Python 3.  Right now that defined type is the only way to use system python and virtualenv on RHEL7 and still works on RHEL8 because the OS provides Python 2.7 packages.

**Pull request closed without merging**
