### PR TITLE
Add ubuntu 18.04 support

### LINKED ISSUE #399: Add Ubuntu 18.04 support
Ubuntu 18.04 got released some time ago. It needs to be tested if the module works on Ubuntu 18.04. If so, the metadata.json needs to be adjusted with Ubuntu 18.04.

### PR DESCRIPTION
**Pull request by danquack**
#### Pull Request (PR) description
I know theres no vagrant image yet (created ticket: see below), but i figured it might be nice to at least run the tests in travis. Not sure if you want to claim that as "supported", but I figured it was a start.

https://tickets.puppetlabs.com/browse/IMAGES-913

#### This Pull Request (PR) fixes the following issues
Partially fixes #399 
This issue should probably stay open until acceptance tests are added, but this is a start to certifying with 18.04.

### CODE REVIEW

**Comment by bastelfreak** [comment]
@danquack FYI there are already acceptance tests: https://github.com/voxpupuli/puppet-python/tree/master/spec/acceptance

As soon as you add ubuntu 18.04 to `.sync.yml` we can merge this.

**Comment by danquack** [comment]
@bastelfreak, I can most certainly add that to the sync file. What I was bringing up, was there’s no nodeset for Ubuntu 18, although this does run it through Travis.

**Comment by bastelfreak** [comment]
A nodeset is not required anymore. They are generated by `BEAKER_setfile=ubuntu1804-64{hypervisor=docker}`.

**Comment by danquack** [comment]
Is it something worth removing all together in a separate PR?

**Comment by bastelfreak** [comment]
Our nodesets come from https://github.com/voxpupuli/modulesync_config/tree/master/moduleroot/spec/acceptance/nodesets. I did not test the generator for anything except docker nodesets. If you want you can open an issue on https://github.com/voxpupuli/modulesync_config to discuss the removal. We already purged all the docker nodesets.

**Pull request merged**
